server:
  port: 20000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.133.129:3306/SpringBootBasic?useSSL=false&serviceTimezone=GMT%2b8
    username: huhuiyu
    password: MySQL-123
logging:
  file: springbase.log
  level:
    com:
      touma: debug
mybatis:  config-location: classpath:mybatis-config.xml